name: Second Workkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Print Greeting
        run: echo Hello World
      - name: Print GoodBye
        run: echo GoodBye
